### ISSUE TITLE
libparasail-sys: Caused by: Failed to build a native library through cargo

### ISSUE THREAD

**Issue by davidlougheed** [nsbuitrago/parasail-rs#5]
Hello,

I'm working on a Docker image with `ENV PARASAIL_NO_VENDOR=0` set to try to force building Parasail in the image.

However, this fails with the following error:

```
#17 57.22         [...]
#17 57.22         --- stderr
#17 57.22         thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libparasail-sys-0.1.6/build.rs:103:14:
#17 57.22         called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
#17 57.22         note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#17 57.22       warning: build failed, waiting for other jobs to finish...
#17 57.22       💥 maturin failed
#17 57.22         Caused by: Failed to build a native library through cargo
#17 57.22         Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/usr/local/bin/python" PYTHON_SYS_EXECUTABLE="/usr/local/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/pip-install-vusmdtgp/strkit-rust-ext_fd9c7587ef434d2bb34a821cfb4ff878/Cargo.toml" "--release" "--lib"
```

It's hard to get much info about why this failure happens, since it comes from `cmake` failing to build, but there's no way to see the log as far as I can tell.

EDIT: worth noting this is on an aarch64 image

**Comment by nsbuitrago** [comment]
Hi, I can take a look at this today. By any chance is the parasail submodule just missing?

**Comment by davidlougheed** [comment]
In the end I "fixed" it by prebuilding a binary instead outside of the docker context; I don't think the parasail submodule is missing - I'm just building a project with `parasail-rs` as a dependency while compiling parasail from scratch rather than using the system library (but maybe cargo isn't getting every piece properly?)

**Comment by nsbuitrago** [comment]
Curios. I was able to get parasail-rs to build in a container but you may need to add cmake and clang depending on which image you are starting from. For example, here's my dockerfile contents using the latest rust image. I could create new rust project and add parasail-rs as a dependency / build it.

```Dockerfile
FROM rust:latest 
WORKDIR /
RUN apt-get update && apt-get install -y \
    cmake \
    make \
    git \
    g++ \
    clang \
    && rm -rf /var/lib/apt/lists/*
```

If possible could you share your dockerfile just to make sure I have the same setup.

**Comment by davidlougheed** [comment]
Missing clang etc is probably it! Part of the reason I reported this was just that I wasn't sure where the error was coming from based on log output. It makes sense that it was happening on aarch64 then, because the dependency is part of a `PyO3` package where I had a prebuilt wheel for AMD64 but not aarch64.

Here's a minimal Dockerfile which gives the same error:

```Dockerfile
FROM python:3.12-bookworm

RUN curl https://sh.rustup.rs -sSf > rustup-init.sh
RUN sh ./rustup-init.sh -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /
RUN mkdir src
RUN printf '[package]\nname = "test"\nversion="0.1.0"\nedition="2021"\n' > Cargo.toml
RUN printf 'fn main() {\nprintln!("hello world");\n}\n' > src/main.rs
RUN cargo add parasail-rs
RUN cargo build
```

**Comment by nsbuitrago** [comment]
I think that was it. The error was not clear at all. I'll see what I can do about adding the cmake crate as a dependency to avoid this in the future. For reference, adding cmake and clang packages work for me.

```Dockerfile
FROM python:3.12-bookworm

RUN curl https://sh.rustup.rs -sSf > rustup-init.sh
RUN sh ./rustup-init.sh -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN apt-get update && apt-get install -y \
    cmake \
    clang

WORKDIR /
RUN mkdir src
RUN printf '[package]\nname = "test"\nversion="0.1.0"\nedition="2021"\n' > Cargo.toml
RUN printf 'fn main() {\nprintln!("hello world");\n}\n' > src/main.rs
RUN cargo add parasail-rs
RUN cargo build
```

**Comment by davidlougheed** [comment]
nice, thank you for your quick response!
