### ISSUE TITLE
Can this repo replace the needle in EMBOSS？

### ISSUE THREAD

**Issue by firemax19** [nsbuitrago/parasail-rs#6]
i'm a noob in both bioinfo and rust, I am looking for a rust crate that can replace the needle function in EMBOSS

**Comment by nsbuitrago** [comment]
Hi. Short answer is yes. Needle should be comparable to global alignment with parasail-rs. There may be some differences depending on how certain cases (such as multiple optimal alignments) are handled, but generally they should yield results that are fairly consistent if using the same parameters. By default, aligners use the global option or you can also set it explicitly (`Aligner::new().global().build()`).

There are also other crates that provide global alignment such as [rust-bio](https://github.com/rust-bio/rust-bio) which you might be interested in checking out as well if you are newer to bioinformatics.

**Comment by firemax19** [comment]
> Hi. Short answer is yes. Needle should be comparable to global alignment with parasail-rs. There may be some differences depending on how certain cases (such as multiple optimal alignments) are handled, but generally they should yield results that are fairly consistent if using the same parameters. By default, aligners use the global option or you can also set it explicitly (`Aligner::new().global().build()`).
> 
> There are also other crates that provide global alignment such as [rust-bio](https://github.com/rust-bio/rust-bio) which you might be interested in checking out as well if you are newer to bioinformatics.

thx for your reply，but Rust bio cannot customize the matrix, which results in comparison results that cannot be consistent with the EMBOSS needle function. Moreover, when I compared a pair of R1R2, Rust bio took twice as long as Parasail
